### ISSUE TITLE
在run.py中读取文件有个报错

### ISSUE THREAD

**Issue by jahaur1** [NanakiC/LCDFormer#3]
CUDA: True cuda:0
Read configuration file: configurations/PEMS04.conf
total training epoch, fine tune epoch: 50 , 25
batch_size: 4
folder_dir: LCDFormer_h7d4w1
load file: ./data/PEMS04\PEMS04_r7_d4_w1.npz
Traceback (most recent call last):
  File "E:\Project2024\Time Series\LCDFormer-main\LCDFormer-main\run.py", line 327, in <module>
    train_loader, train_target_tensor, val_loader, val_target_tensor, test_loader, test_target_tensor, _max, _min = load_graphdata_normY_channel1(
  File "E:\Project2024\Time Series\LCDFormer-main\LCDFormer-main\run.py", line 197, in load_graphdata_normY_channel1
    file_data = np.load(filename)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\numpy\lib\npyio.py", line 420, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "E:\anaconda3\envs\pytorch\lib\site-packages\numpy\lib\npyio.py", line 187, in __init__
    _zip = zipfile_factory(fid)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\numpy\lib\npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "E:\anaconda3\envs\pytorch\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "E:\anaconda3\envs\pytorch\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by jahaur1** [comment]
Sorry, this is a small error I read on the USB flash drive
